### ISSUE TITLE
KeyError: 'state_dict' when loading weights during training

### ISSUE THREAD

**Issue by nadiaparsell** [pkunliu/Isotropic3D#4]
When attempting to train using the following command:

python launch.py --config configs/isotropic3d-shading.yaml --train --gpu 0 system.weights=ckpt/isotropic3d.ckpt

I encountered the following error: 

Traceback (most recent call last):
File "/media/general_00/nadia15/Isotropic3D/launch.py", line 238, in <module>
    main(args, extras)
File "/media/general_00/nadia15/Isotropic3D/launch.py", line 105, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
File "/media/general_00/nadia15/Isotropic3D/threestudio/systems/base.py", line 43, in __init__
    self.load_weights(self.cfg.weights, self.cfg.weights_ignore_modules)
File "/media/general_00/nadia15/Isotropic3D/threestudio/systems/base.py", line 47, in load_weights
    state_dict, epoch, global_step = load_module_weights(
File "/media/general_00/nadia15/Isotropic3D/threestudio/utils/misc.py", line 41, in load_module_weights
    state_dict = ckpt["state_dict"]
KeyError: 'state_dict'

I downloaded the checkpoint file from the hugging face link. I checked the checkpoint file and printed the available keys, but it seems there is no state_dict key. Is it possible the model weights are saved under a different key? Thank you!

**Comment by pkunliu** [comment]
The command you used is incorrect. Please refer to the training instructions in the README.
